### ISSUE TITLE
japanese help file(eregex.jax) has been garble on my Mac

### ISSUE THREAD

**Issue by KiYugadgeter** [othree/eregex.vim#16]
I think its encoding should be UTF-8.

**Comment by othree** [comment]
Do you think its popular to use UTF-8 terminal in Japan?

**Comment by KiYugadgeter** [comment]
I think shift-jis is most popular encoding in japan.
Because, it has been used on Windows.

However, a lot of unix like systems (Linux, Mac) has been used utf-8 by
default.
So I think eregex.jax encoding should be utf-8.

2015-05-12 10:46 GMT+09:00 othree <notifications@github.com>:
