### ISSUE TITLE
foldopen=search does not work when using eregex

### ISSUE THREAD

**Issue by digital-carver** [othree/eregex.vim#19]
Having `set foldopen+=search` is supposed to give this behaviour: when you search for something and the result happens to be within an area that is currently folded, the folds will automatically be opened to show the search result. 

This setting doesn't work when using eregex because this behaviour is disabled by Vim when the search is performed as part of a mapping (or apparently, as in this case, an `exec` command).   
From `help 'foldopen'`:

> 	NOTE: When the command is part of a mapping this option is not used.
>	Add the |zv| command to the mapping to get the same effect.

Adding these lines at line 779 of `plugin/eregex.vim` under the `if v:errmsg ==# ''` clause: 

```
        if &foldenable
            exec 'normal!zv'
        endif
```

appears to correct this problem. 

Could you please add this to the official plugin code?

**Comment by othree** [comment]
Thank you
